

services:
  # PostgreSQL Database
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # NestJS App
  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_2BltfHGyTzD7@ep-spring-scene-a1fx8g7u-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      JWT_SECRET: "your-strong-secret-here"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: